DEFAULT:
  shoulddeletejob: true
  poolvmsize: STANDARD_D1_V2
  poolvmcount: 1

Batch:
  batchaccountname:
  batchaccountkey:
  batchserviceurl:

Storage:
  storageaccountname:
  storageaccountkey:
  storageaccountsuffix: