Pool:
  shoulddeletejob: false 
  poolvmsize: standard_a3 #standard_d3_v2
  poolvmcount: 3
  id: testpoolAPI

Batch:
  batchaccountname: 
  batchaccountkey:  
  batchserviceurl:  

Storage:
  storageaccountkey:  
  storageaccountsuffix:
  connectionstring: 

Registry:
  registryserver: 
  username: 
  password: 
  image_driver: 
  image_worker: 
  image_rabbitmq: 
  image_user: 

