user_image: '2'
MLOS:
    input_simple_hypergrid:
        dimensions: 
            ContinuousDimension: 
                name: shared_buffers
                min: 128 
                max: 1024
    output_simple_hypergrid:
        dimensions: 
            ContinuousDimension:
                name: avg_latency
                min: 5
                max: 15
        objective: avg_latency
        minimize: True
    bayesian_optimizer_config:
        start: default
        random_suggestions_fraction: 0.1
        random_forest: True
        random_forest_refit_sample: 1
        random_forest_splitter: best
        random_forest_samples_fraction_per_estimator: 0.9
        random_forest_n_estimators: 100
        random_forest_confidence_bound: 0.1
    stopping_condition:
        iteration_count: 3
        #max_cost: 
        #max_time:

deployment: LOCAL
source_dir: /home/azureuser/executor
driver_setup: master.yml
worker_setup: worker.yml

LOCAL:
    local_node_ip_address: 10.0.0.4
    mount_point: 
    backup_mount_point:  
    instance_type:
        name: local
        cpuset_cpus_driver: 0-3
        cpuset_cpus_workload: 4-7
        mem_limit_driver: 8G
        mem_limit_workload: 8G
        deploy_dir:
        pool_node_count: 1

AZURE_BATCH:
    Pool:
        shoulddeletejob: false 
        poolvmsize: standard_a3 #standard_d3_v2
        poolvmcount: 3
        id: testpoolAPI
    Batch:
        batchaccountname: 
        batchaccountkey:  
        batchserviceurl:  
    Storage:
        storageaccountkey:  
        storageaccountsuffix:
        connectionstring: 
    Registry:
        registryserver: 
        username: 
        password: 
        image_driver: 
        image_worker: 
        image_rabbitmq: 
        image_user: 


# CLOUD_LAB:
#   master_node_ip_address: 10.10.1.1
#   instance_type:
#   mount_point:
#   user:
#   user_dir:
#   deploy_dir:
#   private_key_filepath:
#   linux_packages:
#   framework_packages:
#   python_packages:
